default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

production:
  primary:
    <<: *default
    database: matrix_dut9

  cable:
    <<: *default
    database: matrix_dut9

  queue:
    <<: *default
    database: matrix_dut9