default: &default
  adapter: postgresql # or sqlite3, depending on what you use locally
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: brain_power_development # The name of your local database

# Keep your existing production block down here
production:
  # ...

production:
  url: <%= ENV.fetch("DATABASE_URL", "") %>